# This file was generated by GoReleaser. DO NOT EDIT.
cask "citadel" do
  version "0.0.5"

  on_macos do
    on_arm do
      sha256 "12e1c2f67118b532c7fae7d11969a12b1bff885f304b301b2d1e47d806561d6f"
      url "https://github.com/vipul0092/citadel/releases/download/v#{version}/citadel-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_arm do
      sha256 "437370b1042adacc6ec3aaeeb1e7882bc9953637da42201847b2a0f9f51df04b"
      url "https://github.com/vipul0092/citadel/releases/download/v#{version}/citadel-linux-arm64.tar.gz"
    end
  end

  name "citadel"
  desc "Terminal LAN chat — auto-discover servers, connect, and chat from the terminal"
  homepage "https://github.com/vipul0092/citadel"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "citadel"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/citadel"]
  end

  # No zap stanza required

end
