# This file was generated by GoReleaser. DO NOT EDIT.
cask "citadel" do
  version "0.0.4"

  on_macos do
    on_arm do
      sha256 "179f069c92e15b5718c60ec620460bd1c33fe230c158e6700fdb4307884d9bbf"
      url "https://github.com/vipul0092/citadel/releases/download/v#{version}/citadel-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_arm do
      sha256 "26679bb035624a4a2381eef0e666ccb9627951482fa32dfd3cef898edae42328"
      url "https://github.com/vipul0092/citadel/releases/download/v#{version}/citadel-linux-arm64.tar.gz"
    end
  end

  name "citadel"
  desc "Terminal LAN chat — auto-discover servers, connect, and chat from the terminal"
  homepage "https://github.com/vipul0092/citadel"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "citadel"

  # No zap stanza required

end
