# This file was generated by GoReleaser. DO NOT EDIT.
cask "citadel" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "5441102b516767be883e55abea79fb5ce3f4044cd4c289b24783920bea3e87cc"
      url "https://github.com/vipul0092/citadel/releases/download/v#{version}/citadel-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_arm do
      sha256 "e343f73e66873742527ebd9b339ae69ecd4ef827dac5a4648a3a9faa04c57cab"
      url "https://github.com/vipul0092/citadel/releases/download/v#{version}/citadel-linux-arm64.tar.gz"
    end
  end

  name "citadel"
  desc "Terminal LAN chat — auto-discover servers, connect, and chat from the terminal"
  homepage "https://github.com/vipul0092/citadel"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "citadel"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/citadel"]
  end

  # No zap stanza required

end
